#!/usr/bin/env bash

declare -r FACTORY_INSTALL_RESET_FILE="/mnt/stateful_partition/factory_install_reset"
declare -r CLOBBER_PARAMS="fast safe keepimg preserve_lvs reason=cmd_request"

clobber() {
  echo "$CLOBBER_PARAMS" > "$FACTORY_INSTALL_RESET_FILE"
  echo "Now restart the device to perform a powerwash, or execute \`clobber cancel\` to cancel."
}

cancel_clobber() {
  rm -f "$FACTORY_INSTALL_RESET_FILE"
  echo "Clobber cancelled"
}

main() {
  if [[ "$1" = "force" ]]; then
    clobber
    exit 0
  elif [[ "$1" = "cancel" ]]; then
    cancel_clobber
    exit 0
  fi

  local input=""
  echo "After executing this command and rebooting, all user data will be erased."
  read -r -p "Type \"yes\" to continue, or enter anything else to abort: " input
  if [[ ! "$input" = "yes" ]]; then
    echo "Aborted"
    exit 0
  fi

  clobber
}

main "$@"
